### ISSUE TITLE
Add there examples to the HBase book

### ISSUE THREAD

**Issue by futurely** [ndimiduk/hbase-1.0-api-examples#2]
It was exciting to hear about the new API. Unfortunately, the [coverage of the new API in the document](http://hbase.apache.org/book.html#hbase_apis) is far from 100%. It feels like failing to find out how to buy a new type of mobile phone after a great marketing campaign.

**Comment by ndimiduk** [comment]
HBase project is always looking for documentation help. Better to take this issue over to https://issues.apache.org/jira/browse/HBASE
